### PR TITLE
Added screen recordings of functions and took screenshots

### PR DESCRIPTION
**Pull request by Tch4lla**
I hope these are what you were looking for. I kept the file names the same in case they were referenced somewhere in the code base

### CODE REVIEW

**Comment by Tch4lla** [comment]
Reaching out again as it has been a fortnight without any conformation about the status of this pull request.

**Comment by rugk** [comment]
Hi @Tch4lla,
thanks for your first contribution to this project! :tada: :+1: 🏅
I hope you'll like this project and enjoy hacking on it… :smiley:

You can (automatically) [let issues close](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) when a PR is merged by adding some "magic" text to your PR _body_. (Manually linked it now.)

BTW: Next time, try to avoid doing a pull request from the master branch, because you can run into problems when you have a "non-clean" master that does not follow this repo here (i.e. "upstream"). [See this article for details](https://help.github.com/en/articles/proposing-changes-to-your-work-with-pull-requests). Anyway, this is only a tip for the next time. :smiley:

**Review by rugk — CHANGES_REQUESTED** [review]
Hi and thanks again, these look very good.

Some notes, though:
* Note that your `qrText.gif` accidentially I guess (or hope) shows an kinda "incorrect" usage, unfortunately: The add-on as shown automatically selects the whole text for you, but you anyway clicked somewhere and double- (or triple) clicked to select the whole text.
That was just an unnecessary step and to show that in an official demo is likely not that optimal. (So people know it is easier than what you showed there.)
* [qrBig.png](https://github.com/rugk/offline-qr-code/pull/284/files#diff-1b3703a865062b34d66f19fd1549f735a392bc38bddc135fee5f086a5245edd0) shows example.org, which is okay, but I used the GitHub URL before as that as again some useful ressource for visitors and a longer URL, where a big QR code makes sense. So again I would prefer to keep that bigger one.
* [qrSettings.png](https://github.com/rugk/offline-qr-code/pull/284/files#diff-c8d79712bef29e5bc9f5ae4ab62423a10b76f1d037e864b4503a95bdfd943d44) should show the _settings_ of the add-on. As such, please switch to "options" and create a screenshot of the whole page (not the add-on description). It may be needed you access the add-on via [Firefox extension devtools](https://extensionworkshop.com/documentation/develop/#test-and-debug) and take a screenshot there](https://firefox-source-docs.mozilla.org/devtools-user/taking_screenshots/index.html) if the options page is too long for your screen.

So if you wanted to correct that, that would be great.

**Comment by rugk** [comment]
Also note BTW if https://github.com/rugk/offline-qr-code/pull/286 is merged (you can try out the test branch already), we can demonstrate another feature as a GIF, i.e. copy text into clipboard and then opening the add-on popup.
That is not really needed for this here/yet, but I just wanted to say that.

**Comment by Tch4lla** [comment]
Ahh I should have commented here. I have made a separate pull request, so I will close this one since the other has all of the changes in the way that you have asked, including the new branch

**Comment by rugk** [comment]
No need for a separate PR, but thanks.

**Pull request closed without merging**
