### PR TITLE
Added Spanish Translation

### PR DESCRIPTION
**Pull request by Fanksies**
Greetings,
Attached you'll find my humble PR which localizes `messages.json` to Latin American Spanish. 
Any feedback will be appreciated. Looking forward to help more with this project.  (Will probably do `assets/texts` next sometime after work)
Thanks!

### CODE REVIEW

**Review by rugk — APPROVED** [review]
Hi @Fanksies,
thanks for your first contribution to this project! :tada: :+1: 🏅
I hope you'll like this project and enjoy hacking on it… :smiley:

As for a review, this LGTM.

As you already noticed there are more things to translate like the add-on listings on AMO (addons.mozilla.org) etc. [See the contributing guide for more information.](https://github.com/TinyWebEx/common/blob/master/CONTRIBUTING.md#translation-of-add-on-listings)

Please subscribe to #138 to get notified for new updates on translations etc. :smiley:

Let me know if this is mergable.

**Comment by Fanksies** [comment]
Its done!
I added a second commit translating the AMO materials and all the stuff I could find inside `assets/texts` check it out when you get the opportunity.

If everything looks good, this should be mergable now. 

Cheers.

**Comment by rugk** [comment]
I'd like to apologize for the delay and I'm sorry this took so long.


BTW: Next time, try to avoid doing a pull request from the master branch, because you can run into problems when you have a "non-clean" master that does not follow this repo here (i.e. "upstream"). [See this article for details](https://help.github.com/en/articles/proposing-changes-to-your-work-with-pull-requests). Anyway, this is only a tip for the next time. :smiley:

**Comment by rugk** [comment]
I've now merged it.
If you want to improve the translations, feel free to have a look at the translation tool again and help to e.g. fix missing translations, verify that the translations are accurate or update outdated ones, etc. as [per our contributing guide](../blob/master/CONTRIBUTING.md#translations).

**Pull request merged**
