### PR TITLE
Issue 173 - Credit translator

### PR DESCRIPTION
**Pull request by nicolas-trouin**
# Fixes Issue #173 

Well this seems to work.
I am sure there are still many improvements to do, so if there's something I can do, let me know 😉 

### Example with browser configured in french : 
fr

### Example with browser configured in german, where the english text is shown : 
en

### CODE REVIEW

**Comment by rugk** [comment]
Thanks. I've changed the styling a little and fixed some issues in the Localizer lib. Also added the English example and adjusted the text/i18n selectors.

This is how it looks now:
image

BTW, also written the corresponding doc for this at https://github.com/TinyWebEx/common/blob/master/CONTRIBUTING.md#translator-credit-inside-of-add-on

**Comment by rugk** [comment]
BTW to (automatically) [let issues close](https://help.github.com/articles/closing-issues-via-commit-messages/) when a PR is merged, write "fixes" before the issue number (in your heading here).

**Comment by rugk** [comment]
BTW, _after_ this is merged, and _if_ you also want to do the same PR for the other add-ons (backlinks above this comment), then feel free to do so… :smile:

**Comment by nicolas-trouin** [comment]
> BTW, _after_ this is merged, and _if_ you also want to do the same PR for the other add-ons (backlinks above this comment), then feel free to do so… 😄

I'll check it out ^^'

**Comment by nicolas-trouin** [comment]
### French translation

image

Is that fine ?


I also spotted a spacing problem with the english translation, as shown below : 

image

Should I try to solve it ?

**Comment by rugk** [comment]
Likely you just need to run `git submodule update` to sync the submodules to the new state I have commit them… (bad git does not do this automatically)

(Because that did not happen in my case.)

**Comment by nicolas-trouin** [comment]
> Likely you just need to run `git submodule update` to sync the submodules to the new state I have commit them… (bad git does not do this automatically)
> 
> (Because that did not happen in my case.)

Yep that solved the problem. Anything else I can do about the french translation or other ?

**Comment by rugk** [comment]
>  I can do about the french translation or other ?

I don't know whether it's still the case, but there likely should not be a space before the `!` at the end of the sentence.

**Comment by nicolas-trouin** [comment]
> I don't know whether it's still the case, but there likely should not be a space before the `!` at the end of the sentence.

Well, I think you'd be right for English or German, but in French there has to be a single space before and after "!", "?", ";", and maybe others too.

**Comment by rugk** [comment]
> > BTW, after this is merged, and if you also want to do the same PR for the other add-ons (backlinks above this comment), then feel free to do so… smile
>
> I'll check it out ^^'

BTW, let me know in https://github.com/rugk/awesome-emoji-picker/issues/18 and https://github.com/rugk/mastodon-simplified-federation/issues/25 if you want to solve that. :smile:

**Pull request merged**
