### PR TITLE
Fixed #102 feature 'Remember last size'.

### LINKED ISSUE #102: Remember last size does work as expected
I changed the QR code size option to 'remember the last size' but it could not restore to the previous size on next launch.
Windows 10
Firefox 60.0.2

### PR DESCRIPTION
**Pull request by AmauriAires**
- Added variable initialClick to control when the qrCode is resized.

### CODE REVIEW

**Comment by rugk** [comment]
Hi @AmauriAires,
thanks for your first contribution to this project! 🎉 👍 Nice to see you on here. 😊
I hope you'll like this project and can enjoy hacking on it… 😃

So that fix looks interesting. Can you explain a bit more why it does help to fix the issue? Best do it by adding some comments to the source, so it is also understandable by someone later.

Also there are some minor code style issues:
* avoid global variables, in this case put the var into the "class" (I.e. the module), where it is used
* the else keyword should be on the same line as the closing bracket before

For more details, see eslint/the Contribung.md.

**Comment by AmauriAires** [comment]
Thank you for your reply. I have made some changes on fix-remember-last-size. Please let me know if there is anything else to be corrected.

**Comment by rugk** [comment]
Totally unrelated to this PR, but just FYI: The git commits are not assigned to your GitHub account (you can e.g. see they do not show your profile picture). This likely happens, because [you did not configured your GitHub username](https://help.github.com/articles/setting-your-username-in-git/)[/email in git](https://help.github.com/articles/setting-your-commit-email-address-in-git/).

**Comment by rugk** [comment]
So if you want a tip, maybe `UserInterface.lateInit` can help here. I introduced this only recently, because there is other stuff that may collide when it is executed too early.

If you test it, please make sure to test all variants one can open the QR code popup (like select text, shortcut, etc.) – because many use different ways of passing the QR code text to the popup and that may happen at different times.

**Comment by rugk** [comment]
Another BTW: You can (automatically) [let issues close](https://help.github.com/articles/closing-issues-via-commit-messages/) when a PR is merged.

**Comment by rugk** [comment]
Sure, just do it in this PR. The "fix #102" should just be mentioned in the PR description (i.e. [at the top](https://github.com/rugk/offline-qr-code/pull/103#issue-196000725)) for "auto-closing" to work. You can edit that, though.

**Comment by AmauriAires** [comment]
From my research, I observed that MutationObservers, by nature, do not wait until all resources have finished loading/rendering unless we implement that functionality (https://eager.io/blog/three-real-world-use-cases-for-mutation-observer/). Based on that, I decided to add an addEventListener to make sure the MutationObserver would only start observing changes after all resources had finished loading.

**Comment by AmauriAires** [comment]
Please let me know if this fix is proper now.

**Comment by rugk** [comment]
Upps, accidentally already merged this, but then notices it actually does not work. The whole MutationResizer did not work. In my case it just does not fire/react in any way. (i.e. you can see the resizing does not happen)

This also happened to me before, when I create the variable too late, for some reason initiating it earlier makes it work while doing it later does not.

As GitHub shows this as merged (and does not seem to get I "unmerged" it) feel free to create a new PR. I guess I cannot merge this one here "a second time" :smile:.

**Pull request merged**
