### PR TITLE
Update Spanish translations with a few orthographic corrections

### PR DESCRIPTION
**Pull request by dverbru**
#325

### CODE REVIEW

**Comment by rugk** [comment]
Hi @dverbru,
first of all, thanks for your first contribution to this project! :tada: :+1: 🏅
I hope you'll like this project and enjoy hacking on it… :smiley:

Please subscribe to #138 to get notified for new updates on translations etc. :smiley:

BTW you can (automatically) [let issues close](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) when a PR is merged by adding some "magic" text to your PR _body_. (Manually linked it now.)

Also notice there are more things to translate like the add-on listings on AMO (addons.mozilla.org) etc. [See the contributing guide for more information.](https://github.com/TinyWebEx/common/blob/master/CONTRIBUTING.md#translation-of-add-on-listings)

**Review by rugk — COMMENTED** [review]
Requesting a potential review from @Fanksies and @bryancalisto. Unless there are objections, this will be merged soon.

@dverbru 
To honor your work, you should be credited in the extension. To do that, you need to provide your name and a link in the extension.

You can credit yourself here and provide a link (in `translatorLink`) and a name (in `translatorUsername`). Also, you should add yourself to the CONTRIBUTORS.md file and the changelog as a translator to [give credits here](https://github.com/TinyWebEx/common/blob/master/CONTRIBUTING.md#credit).

See https://github.com/TinyWebEx/common/blob/master/CONTRIBUTING.md#translations for how these placeholders are translated, especially [the official doc](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/Internationalization#Providing_localized_strings_in__locales).

BTW note if you want you can also write the Changelog entry already, just copy an existing one [as explained as a side-note here](https://github.com/TinyWebEx/common/blob/master/CONTRIBUTING.md#credit).

**Comment by dverbru** [comment]
Added myself to CONTRIBUTORS file, thanks. Anything else?

**Review by bryancalisto — APPROVED** [review]
It looks good to me. Question marks consistent with Spanish conventions and overall semantically correct.

**Review by rugk — APPROVED** [review]
Fine, thanks a lot to everybody involved!

**Pull request merged**
