### PR TITLE
Some minor word and link changes

### PR DESCRIPTION
**Pull request by ENT8R**

### CODE REVIEW

**Comment by rugk** [comment]
Hi @ENT8R,
thanks for your first contribution to this project! :tada: :+1: Nice to see you on here. :blush: 
I hope you'll like this project and can enjoy hacking on it… :smiley:

And thanks for the small fixes.
I'll just also need the same changes in the AMO description (under `assets/texts`), as they use mostly the same text as the Readme.

**Comment by rugk** [comment]
If you want, sure. Maybe you spot some other issues when reading it. :wink:

**Comment by ENT8R** [comment]
I'm doing this right now and I really spot some more issues 😄

**Comment by ENT8R** [comment]
I think so, yes!

**Pull request merged**
